name: Build AMI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-ami:
    runs-on: ubuntu-latest
    
    container:
      image: hashicorp/packer:latest
      options: --user root -v /var/run/docker.sock:/var/run/docker.sock

    steps:
      - name: Set up Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          node-version: 20

      - name: Configure AWS credentials
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          mkdir -p ~/.aws
          echo "[default]" > ~/.aws/credentials
          echo "aws_access_key_id=${{ secrets.AWS_ACCESS_KEY_ID }}" >> ~/.aws/credentials
          echo "aws_secret_access_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> ~/.aws/credentials

      - name: Initialize Packer
        run: packer init aws-ami-v1.pkr.hcl

      - name: Build AMI
        run: packer build aws-ami-v1.pkr.hcl
